
package samples.services.arraymultiplicationtest;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ArrayMultiplication", targetNamespace = "http://multiplicationstresstest.services.samples/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ArrayMultiplication {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Long>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "arrayMultiplication", targetNamespace = "http://multiplicationstresstest.services.samples/", className = "samples.services.arraymultiplicationtest.ArrayMultiplication_Type")
    @ResponseWrapper(localName = "arrayMultiplicationResponse", targetNamespace = "http://multiplicationstresstest.services.samples/", className = "samples.services.arraymultiplicationtest.ArrayMultiplicationResponse")
    public List<Long> arrayMultiplication(
        @WebParam(name = "arg0", targetNamespace = "")
        List<Integer> arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<Integer> arg1);

}
