/*
 * Copyright (c) 2010-2014 AdroitLogic Private Ltd. All Rights Reserved.
 */

package samples.services.arraymultiplicationtest;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ArrayMultiplicationService", targetNamespace = "http://multiplicationstresstest.services.samples/", wsdlLocation = "http://localhost:9000/service/ArrayMultiplication?wsdl")
public class ArrayMultiplicationService
    extends Service
{

    private final static URL ARRAYMULTIPLICATIONSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(samples.services.arraymultiplicationtest.ArrayMultiplicationService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = samples.services.arraymultiplicationtest.ArrayMultiplicationService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:9000/service/ArrayMultiplication?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:9000/service/ArrayMultiplication?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ARRAYMULTIPLICATIONSERVICE_WSDL_LOCATION = url;
    }

    public ArrayMultiplicationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ArrayMultiplicationService() {
        super(ARRAYMULTIPLICATIONSERVICE_WSDL_LOCATION, new QName("http://multiplicationstresstest.services.samples/", "ArrayMultiplicationService"));
    }

    /**
     * 
     * @return
     *     returns ArrayMultiplication
     */
    @WebEndpoint(name = "ArrayMultiplicationPort")
    public ArrayMultiplication getArrayMultiplicationPort() {
        return super.getPort(new QName("http://multiplicationstresstest.services.samples/", "ArrayMultiplicationPort"), ArrayMultiplication.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ArrayMultiplication
     */
    @WebEndpoint(name = "ArrayMultiplicationPort")
    public ArrayMultiplication getArrayMultiplicationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://multiplicationstresstest.services.samples/", "ArrayMultiplicationPort"), ArrayMultiplication.class, features);
    }

}
